spring:
  application:
    name: Discovery Servers

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    response-cache-update-interval-ms: 30
    registry-sync-retries: 5
    wait-time-in-ms-when-sync-empty: 300
